# Generated by Django 5.2.13 on 2026-04-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('time_based', 'Time Based')], default='time_based', max_length=10),
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('available', 'Available'), ('maybe', 'Maybe'), ('unavailable', 'Unavailable')], default='available', max_length=15),
        ),
    ]
